name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "f89085dc1bbf42a99fe8533db4495acb"				#KV数据库id

[[workflows]]
binding = "KV_WORKFLOW"
name = "kv-workflow"
class_name = "KVWorkflow"